# Simplified Render.com Deployment Configuration for AgentGuard
services:
  # Main API Service
  - type: web
    name: agentguard-api
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT --workers 2
    healthCheckPath: /health
    
    # Environment Variables
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: false
      
      # API Keys (set these in Render dashboard)
      - key: CLAUDE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      
      # Database (optional - will use SQLite if not provided)
      - key: DATABASE_URL
        sync: false
      
      # Redis (optional - caching will be disabled if not provided)
      - key: REDIS_URL
        sync: false
      
      # Security
      - key: JWT_SECRET
        generateValue: true
      - key: API_KEY_SECRET
        generateValue: true
      
      # CORS
      - key: CORS_ORIGINS
        value: "*"
      
      # Feature Flags
      - key: ENABLE_MULTIMODAL
        value: true
      - key: ENABLE_BIAS_AUDITING
        value: true
      - key: ENABLE_RED_TEAMING
        value: true
      - key: ENABLE_COMPLIANCE_REPORTING
        value: true
      
      # MLflow (optional)
      - key: MLFLOW_TRACKING_URI
        value: ""
      - key: MLFLOW_EXPERIMENT_NAME
        value: agentguard_production
    
    # Auto-deploy settings
    autoDeploy: true
    branch: main
    
    # Health check configuration
    healthCheck:
      path: /health
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 3
