# AgentGuard Monorepo - Render.com Deployment Configuration
# Mothership AI - watcher.mothership-ai.com
# COMPLETE MONOREPO: Both backend API and frontend UI deployed from this single repository on Render
# NO VERCEL - Everything runs on Render

services:
  # Backend API Service - Updated October 2025 (Final Verified Stable)
  - type: web
    name: agentguard-api
    env: python
    runtime: python-3.14.0
    region: oregon
    plan: starter
    rootDir: .
    buildCommand: pip install --upgrade pip && pip install -r requirements-render.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT --workers 2
    healthCheckPath: /health
    
    # Environment Variables for Backend
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: false
      
      # API Keys (set these in Render dashboard)
      - key: CLAUDE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      
      # Database (optional - will use SQLite if not provided)
      - key: DATABASE_URL
        sync: false
      
      # Redis (optional - caching will be disabled if not provided)
      - key: REDIS_URL
        sync: false
      
      # Security
      - key: JWT_SECRET
        generateValue: true
      - key: API_KEY_SECRET
        generateValue: true
      
      # CORS - Allow frontend to access backend
      - key: CORS_ORIGINS
        value: "*"
      
      # Feature Flags
      - key: ENABLE_MULTIMODAL
        value: true
      - key: ENABLE_BIAS_AUDITING
        value: true
      - key: ENABLE_RED_TEAMING
        value: true
      - key: ENABLE_COMPLIANCE_REPORTING
        value: true
      
      # MLflow (optional)
      - key: MLFLOW_TRACKING_URI
        value: ""
      - key: MLFLOW_EXPERIMENT_NAME
        value: agentguard_production
    
    # Auto-deploy settings
    autoDeploy: true
    branch: main
    
    # Health check configuration
    healthCheck:
      path: /health
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 3

  # Frontend UI Service
  - type: web
    name: agentguard-ui
    env: node
    region: oregon
    plan: starter
    rootDir: agentguard-ui
    buildCommand: npm install && npm run build
    startCommand: npm start
    
    # Environment Variables for Frontend
    envVars:
      # API URL - Point to backend service
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: agentguard-api
          envVarKey: RENDER_EXTERNAL_URL
      
      # Application Configuration
      - key: NEXT_PUBLIC_APP_NAME
        value: AgentGuard
      - key: NEXT_PUBLIC_APP_VERSION
        value: 1.0.0
      - key: NEXT_PUBLIC_APP_DESCRIPTION
        value: AI Safety Platform - Production Ready
      
      # Feature Flags
      - key: NEXT_PUBLIC_ENABLE_ANALYTICS
        value: true
      - key: NEXT_PUBLIC_ENABLE_MONITORING
        value: true
      - key: NEXT_PUBLIC_ENABLE_WEBHOOKS
        value: true
      - key: NEXT_PUBLIC_ENABLE_BATCH_PROCESSING
        value: true
      
      # Security
      - key: NEXT_PUBLIC_ENABLE_HTTPS_ONLY
        value: true
      - key: NEXT_PUBLIC_ENABLE_SECURITY_HEADERS
        value: true
      
      # Contact Information
      - key: NEXT_PUBLIC_SUPPORT_EMAIL
        value: info@mothership-ai.com
      - key: NEXT_PUBLIC_COMPANY_NAME
        value: Mothership AI
      - key: NEXT_PUBLIC_COMPANY_URL
        value: https://mothership-ai.com
      - key: NEXT_PUBLIC_DOMAIN
        value: watcher.mothership-ai.com
      
      # Investment Information
      - key: NEXT_PUBLIC_INVESTMENT_SLOTS
        value: 50
      - key: NEXT_PUBLIC_FUNDING_GOAL
        value: 500000
      - key: NEXT_PUBLIC_INVESTOR_DEADLINE
        value: 2025-11-30
      - key: NEXT_PUBLIC_LAUNCH_DATE
        value: 2026-01-01
    
    # Auto-deploy settings
    autoDeploy: true
    branch: main
    
    # Health check
    healthCheckPath: /
