apiVersion: v1
kind: Namespace
metadata:
  name: agentguard
  labels:
    name: agentguard
    app: agentguard
    version: "2025.10"
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: agentguard-quota
  namespace: agentguard
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: agentguard-limits
  namespace: agentguard
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
